### ISSUE TITLE
Remove Supdirectory

### ISSUE THREAD

**Issue by murrant** [swissonid/android-design-support-lib-sample#1]
I tried to import this project directly into Android Studio, but it had an issue because the project is in a subdirectory.  Remove the first directory and it will import directly.  Thanks.

**Comment by amouly** [comment]
+1

**Comment by amouly** [comment]
@murrant I've created a PR for this, do you want to test it on my fork? Thanks.

**Comment by amouly** [comment]
@swissonid you can close this now ;).

**Comment by swissonid** [comment]
I didn't that would be an issue to some one but at the end I'm happy that
all u r happy now with the project setup. I hope u got the infos out of it
that u need

:D

**Comment by amouly** [comment]
@swissonid is not an issue, is more like an standard way to organize the project. Anyway, you can close it, not delete it. Just to keep tracking the real issues ;). Yeah, the community it's really happy with this, thanks putting this together.
