### ISSUE TITLE
Flexible space with overlapping content

### ISSUE THREAD

**Issue by pirakleous** [swissonid/android-design-support-lib-sample#15]
Hello can you please do the Flexible space with overlapping content example as shown i google material specs scrolling technics?

**Comment by vickychijwani** [comment]
+1 for this.

**Comment by swissonid** [comment]
I try to do it after my vacation. So end of August is realistic...I hope
that's fine ;D

**Comment by vickychijwani** [comment]
Yes ok :). This link might help you: http://stackoverflow.com/a/31039075/504611. I _almost_ got it working, except my `RecyclerView` ends up _behind_ the `AppBarLayout`.

**Comment by sweggersen** [comment]
vickychijwani: It's probably because your appbar has a higher elevation than your recyclerview. Try setting the appbarlayouts elevation to 0.
