### ISSUE TITLE
How to make a layout like this one in Spotify?  

### ISSUE THREAD

**Issue by jjvargas** [swissonid/android-design-support-lib-sample#17]
It looks like the Shuffle Play Green Button is like a Sticky header,  any ideas???

![spotify](https://cloud.githubusercontent.com/assets/1838805/8503012/3378ddcc-21b0-11e5-8170-b8b992004311.jpg)

**Comment by QuentinBontemps** [comment]
This looks like a flexible toolbar with a fab

**Comment by swissonid** [comment]
Or any custom view, you could use the anchor attribute
