### ISSUE TITLE
Add googlemap fragment

### ISSUE THREAD

**Issue by youssefbounar** [swissonid/android-design-support-lib-sample#21]
i want to add googlemap fragment in your projet but it didn't work for me
:
SupportMapFragment mapfrag = (SupportMapFragment)getChildFragmentManager().findFragmentById(R.id.map);
.
it give me error null exception in this line.
i need help

**Comment by EminYahyayev** [comment]
@BinoJozef this is an issue tracker, not the stackoverflow. You should ask such questions there.

**Comment by youssefbounar** [comment]
Thanks :)
