### ISSUE TITLE
Toolbar - setSupportActionBar()

### ISSUE THREAD

**Issue by TomasValenta** [swissonid/android-design-support-lib-sample#25]
Hello Patrice,
first thank you for your great work, your logic help me a lot!

I like, that I can change the fragment with toolbar and all layouts together. I have only one question, how to to add to the toolbar "Menu items"?

**Comment by swissonid** [comment]
Hi,

I don't know if I have you understood right, but maybe that will you 
[stackoverflow](http://stackoverflow.com/questions/26489079/evenly-spaced-menu-items-on-toolbar)

If not, I try to add some menu Items in the next commit. 

I wish you a nice weekend and Happy Coding ;D

**Comment by TomasValenta** [comment]
Thank you very much,

I forgot to add:

``` java
toolbar.inflateMenu(R.id.menu);
```

to Base Fragment ;)

**Comment by hardikamal** [comment]
hi @TomasValenta & @swissonid how do i hide this menu item on some fragment...it appears on all fragment if i add the above line in basefragment...

**Comment by TomasValenta** [comment]
Solution can be inflating the menus in child fragments and in every fragment inflate different menu or nothing, take a look to my source code:
https://github.com/TomasValenta/WebCams/blob/master/app/src/main/java/cz/yetanotherview/webcamviewer/app/fragments/MapAppBarFragment.java
