### ISSUE TITLE
Fitssystemwindows does not work from Fragment?

### ISSUE THREAD

**Issue by TomasValenta** [swissonid/android-design-support-lib-sample#26]
Hello again,

"Flexible space with image" example do not overlap the status bar. You know how to fix it?

**Comment by swissonid** [comment]
You have to put it in an separate activity. For more detail how to deal with it, take a look [here](https://github.com/ianhanniballake/cheesesquare/blob/master/app/src/main/java/com/support/android/designlibdemo/CheeseDetailActivity.java)

**Comment by TomasValenta** [comment]
But separate activity is not the solution for me :( I need to do this only with replacing fragments, as does your example, but with status bar overlapping.

**Comment by swissonid** [comment]
Have already saw [that one](http://stackoverflow.com/questions/28205473/androidfitssystemwindows-not-working)

**Comment by TomasValenta** [comment]
No,
and honestly, I don't understand the suggested solution on Stackoverflow ;)
I found also [this](http://stackoverflow.com/questions/31190612/fitssystemwindows-effect-gone-for-fragments-added-via-fragmenttransaction) but the solution method is deprecated.

**Comment by TomasValenta** [comment]
So, the [first solution](http://stackoverflow.com/a/31194954/3796931) from the link above is working fine!
