### ISSUE TITLE
Hamburger icon tint color

### ISSUE THREAD

**Issue by amouly** [swissonid/android-design-support-lib-sample#5]
On some sections, the hamburger icon and the title are black, and other section are withe. Maybe it's a problem with the Style.

You are using "Theme.AppCompat.Light.NoActionBar". Should we use "dark"?

**Comment by swissonid** [comment]
Yes I know. That comes from the light theme to which I recently changed. I
have to implement anyway a toolbar on each fragment which will use the
custom style. I didn't spend any effort to adjust the black actionbar.
On 7 Jun 2015 21:00, "Adrián Mouly" notifications@github.com wrote:

On some sections, the hamburger icon and the title are black, and other
section are withe. Maybe it's a problem with the Style.

—
Reply to this email directly or view it on GitHub
https://github.com/swissonid/android-design-support-lib-sample/issues/5.

**Comment by swissonid** [comment]
I will close this issue...Won't be fixed
