### ISSUE TITLE
Question: why put so much empty space when scrolling in the "flexible" examples?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [swissonid/android-design-support-lib-sample#9]
It seems that for the 2 "flexible" examples, there is a huge amount of empty space at the bottom.
How come?
Will it still work fine without it?

**Comment by swissonid** [comment]
It wouldn't work right now without it. At the moment, I working on a runtime calculation wich should calculate the minimum height of the view. So that you have the nice effect with the minimum of the empty space or even without.

**Comment by AndroidDeveloperLB** [comment]
I see. I thought it looked suspicious.
Say, since you probably know much about scrolling, can you answer this:
I need to have an all-directions scrollview which allows to zoom into views/rectangles (without affecting them). Is there something that you know that can help doing it?
In a WebView, it's quite easy as it's possible to zoom on the page (even using the default touch events), but I can't find anything similar on Android. I've also heard that IOS has it (they call it "ScrollView" too).
